namespace Dockable.Localization;

/// <summary>
/// The in-code string tables for every supported language. Each table maps a stable string key
/// (e.g. <c>Section_System</c>) to its translation; English (<see cref="DefaultCode"/>) is the
/// source-of-truth and the fallback for any key a translation omits. Product names ("Dockable"),
/// brand/tech names (C#, WPF, CsWin32, …) and the author's name are intentionally left untranslated.
/// </summary>
internal static class LocData
{
    /// <summary>The neutral/source language used as the fallback for missing keys.</summary>
    public const string DefaultCode = "en";

    /// <summary>The languages offered in the picker, in display order: (culture code, native name).</summary>
    public static readonly IReadOnlyList<(string Code, string Name)> Languages = new[]
    {
        ("en", "English"),
        ("pt-BR", "Português (Brasil)"),
        ("es", "Español"),
        ("uk", "Уукраїнська"),
        ("zh-Hans", "中文"),
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Window_DockPreferences"] = "Dock Preferences",
        ["Section_System"] = "System",
        ["Section_Appearance"] = "Appearance",
        ["Section_Dock"] = "Dock",
        ["Section_Taskbar"] = "Taskbar",
        ["Row_Language"] = "Language",
        ["Row_OpenAtLogin"] = "Open at login",
        ["Link_StartupApps"] = "Startup Apps",
        ["Theme_Light"] = "Light",
        ["Theme_Dark"] = "Dark",
        ["Theme_Auto"] = "Auto",
        ["Label_Size"] = "Size",
        ["Caption_Small"] = "Small",
        ["Caption_Large"] = "Large",
        ["Label_Magnification"] = "Magnification",
        ["Caption_Off"] = "Off",
        ["Row_Position"] = "Position on screen",
        ["Position_Bottom"] = "Bottom",
        ["Position_Left"] = "Left",
        ["Position_Right"] = "Right",
        ["Position_Top"] = "Top",
        ["Row_GlassEffect"] = "Glass Effect",
        ["Glass_Translucent"] = "Translucent",
        ["Glass_Acrylic"] = "Acrylic",
        ["Glass_LiquidGlass"] = "Liquid Glass",
        ["Row_MinimizeUsing"] = "Minimize windows using",
        ["Minimize_Suck"] = "Suck Effect",
        ["Minimize_Scale"] = "Scale Effect",
        ["Minimize_Genie"] = "Genie Effect",
        ["Label_EffectSpeed"] = "Effect Speed",
        ["Caption_Slow"] = "Slow",
        ["Caption_Default"] = "Default",
        ["Caption_Fast"] = "Fast",
        ["Toggle_ShowIndicators"] = "Show indicators for open applications",
        ["Toggle_AnimateOpening"] = "Animate opening applications",
        ["Toggle_MinimizeIntoIcon"] = "Minimize windows into application icon",
        ["Toggle_HideTaskbar"] = "Automatically hide Windows taskbar",
        ["Tray_ShowHideDock"] = "Show / Hide Dock",
        ["Tray_HideTaskbar"] = "Hide taskbar",
        ["Tray_Theme"] = "Theme",
        ["Menu_DockPreferences"] = "Dock Preferences…",
        ["Menu_AboutDockable"] = "About Dockable",
        ["Menu_Exit"] = "Exit",
        ["Menu_EmptyRecycleBin"] = "Empty Recycle Bin",
        ["Menu_QuitDockable"] = "Quit Dockable",
        ["Menu_NewWindow"] = "New Window",
        ["Menu_Rename"] = "Rename",
        ["Menu_Options"] = "Options",
        ["Menu_KeepInDock"] = "Keep in Dock",
        ["Menu_OpenAtLogin"] = "Open at Login",
        ["Menu_ShowInExplorer"] = "Show in Explorer",
        ["Menu_ShowAllWindows"] = "Show All Windows",
        ["Menu_Quit"] = "Quit",
        ["Menu_ForceQuit"] = "Force Quit",
        ["Dialog_AddToStartup"] = "Would you like to add Dockable to startup?",
        ["Dialog_ReplicatePinsSingular"] = "A new shortcut has been pinned to the taskbar. Would you like to replicate it on the Dock?",
        ["Dialog_ReplicatePinsPlural"] = "New shortcuts have been pinned to the taskbar. Would you like to replicate them on the Dock?",
        ["Dialog_RenameShortcut"] = "Rename this shortcut:",
        ["Common_DoNotAskAgain"] = "Do not ask again",
        ["Common_Yes"] = "Yes",
        ["Common_No"] = "No",
        ["Common_OK"] = "OK",
        ["Common_Cancel"] = "Cancel",
        ["Common_Close"] = "Close",
        ["Error_StartupFailed"] = "Dockable failed to start:\n\n{0}\n\nDetails were written to %APPDATA%\\Dockable\\crash.log.",
        ["About_Tagline"] = "A macOS-style Dock for Windows 11",
        ["About_Version"] = "Version {0}",
        ["About_Body"] = "Dockable brings the macOS Dock experience to Windows 11 — magnifying icons, a glass bar, and a genie-style minimize. It's built with C# and WPF on .NET 9 (x64), with native Win32 interop via CsWin32, MVVM through CommunityToolkit.Mvvm, and a system-tray icon from H.NotifyIcon. Inspired by Apple's macOS Dock.",
        ["About_CreatedBy"] = "Created by",
    };

    private static readonly IReadOnlyDictionary<string, string> PortugueseBR = new Dictionary<string, string>
    {
        ["Window_DockPreferences"] = "Preferências do Dock",
        ["Section_System"] = "Sistema",
        ["Section_Appearance"] = "Aparência",
        ["Section_Dock"] = "Dock",
        ["Section_Taskbar"] = "Barra de tarefas",
        ["Row_Language"] = "Idioma",
        ["Row_OpenAtLogin"] = "Abrir ao iniciar sessão",
        ["Link_StartupApps"] = "Aplicativos de inicialização",
        ["Theme_Light"] = "Clara",
        ["Theme_Dark"] = "Escura",
        ["Theme_Auto"] = "Automática",
        ["Label_Size"] = "Tamanho",
        ["Caption_Small"] = "Pequeno",
        ["Caption_Large"] = "Grande",
        ["Label_Magnification"] = "Ampliação",
        ["Caption_Off"] = "Desligado",
        ["Row_Position"] = "Posição na tela",
        ["Position_Bottom"] = "Inferior",
        ["Position_Left"] = "Esquerda",
        ["Position_Right"] = "Direita",
        ["Position_Top"] = "Superior",
        ["Row_GlassEffect"] = "Efeito de vidro",
        ["Glass_Translucent"] = "Translúcido",
        ["Glass_Acrylic"] = "Acrílico",
        ["Glass_LiquidGlass"] = "Vidro líquido",
        ["Row_MinimizeUsing"] = "Minimizar janelas usando",
        ["Minimize_Suck"] = "Efeito de sucção",
        ["Minimize_Scale"] = "Efeito de escala",
        ["Minimize_Genie"] = "Efeito Aladim",
        ["Label_EffectSpeed"] = "Velocidade do efeito",
        ["Caption_Slow"] = "Lenta",
        ["Caption_Default"] = "Padrão",
        ["Caption_Fast"] = "Rápida",
        ["Toggle_ShowIndicators"] = "Mostrar indicadores de apps abertos",
        ["Toggle_AnimateOpening"] = "Animar abertura de aplicativos",
        ["Toggle_MinimizeIntoIcon"] = "Minimizar janelas no ícone do app",
        ["Toggle_HideTaskbar"] = "Ocultar a barra de tarefas do Windows automaticamente",
        ["Tray_ShowHideDock"] = "Mostrar / Ocultar Dock",
        ["Tray_HideTaskbar"] = "Ocultar barra de tarefas",
        ["Tray_Theme"] = "Tema",
        ["Menu_DockPreferences"] = "Preferências do Dock…",
        ["Menu_AboutDockable"] = "Sobre o Dockable",
        ["Menu_Exit"] = "Sair",
        ["Menu_EmptyRecycleBin"] = "Esvaziar Lixeira",
        ["Menu_QuitDockable"] = "Sair do Dockable",
        ["Menu_NewWindow"] = "Nova janela",
        ["Menu_Rename"] = "Renomear",
        ["Menu_Options"] = "Opções",
        ["Menu_KeepInDock"] = "Manter no Dock",
        ["Menu_OpenAtLogin"] = "Abrir ao iniciar sessão",
        ["Menu_ShowInExplorer"] = "Mostrar no Explorer",
        ["Menu_ShowAllWindows"] = "Mostrar todas as janelas",
        ["Menu_Quit"] = "Encerrar",
        ["Menu_ForceQuit"] = "Forçar encerramento",
        ["Dialog_AddToStartup"] = "Deseja adicionar o Dockable à inicialização?",
        ["Dialog_ReplicatePinsSingular"] = "Um novo atalho foi fixado na barra de tarefas. Deseja replicá-lo no Dock?",
        ["Dialog_ReplicatePinsPlural"] = "Novos atalhos foram fixados na barra de tarefas. Deseja replicá-los no Dock?",
        ["Dialog_RenameShortcut"] = "Renomear este atalho:",
        ["Common_DoNotAskAgain"] = "Não perguntar novamente",
        ["Common_Yes"] = "Sim",
        ["Common_No"] = "Não",
        ["Common_OK"] = "OK",
        ["Common_Cancel"] = "Cancelar",
        ["Common_Close"] = "Fechar",
        ["Error_StartupFailed"] = "Falha ao iniciar o Dockable:\n\n{0}\n\nOs detalhes foram gravados em %APPDATA%\\Dockable\\crash.log.",
        ["About_Tagline"] = "Um Dock no estilo do macOS para o Windows 11",
        ["About_Version"] = "Versão {0}",
        ["About_Body"] = "O Dockable traz a experiência do Dock do macOS para o Windows 11 — ícones com ampliação, uma barra de vidro e uma minimização estilo gênio. Foi desenvolvido em C# e WPF sobre o .NET 9 (x64), com interop nativa do Win32 via CsWin32, MVVM com CommunityToolkit.Mvvm e um ícone na bandeja do sistema com H.NotifyIcon. Inspirado no Dock do macOS da Apple.",
        ["About_CreatedBy"] = "Criado por",
    };

    private static readonly IReadOnlyDictionary<string, string> Spanish = new Dictionary<string, string>
    {
        ["Window_DockPreferences"] = "Preferencias del Dock",
        ["Section_System"] = "Sistema",
        ["Section_Appearance"] = "Aspecto",
        ["Section_Dock"] = "Dock",
        ["Section_Taskbar"] = "Barra de tareas",
        ["Row_Language"] = "Idioma",
        ["Row_OpenAtLogin"] = "Abrir al iniciar sesión",
        ["Link_StartupApps"] = "Aplicaciones de inicio",
        ["Theme_Light"] = "Claro",
        ["Theme_Dark"] = "Oscuro",
        ["Theme_Auto"] = "Automático",
        ["Label_Size"] = "Tamaño",
        ["Caption_Small"] = "Pequeño",
        ["Caption_Large"] = "Grande",
        ["Label_Magnification"] = "Ampliación",
        ["Caption_Off"] = "Desactivado",
        ["Row_Position"] = "Posición en la pantalla",
        ["Position_Bottom"] = "Inferior",
        ["Position_Left"] = "Izquierda",
        ["Position_Right"] = "Derecha",
        ["Position_Top"] = "Superior",
        ["Row_GlassEffect"] = "Efecto de cristal",
        ["Glass_Translucent"] = "Translúcido",
        ["Glass_Acrylic"] = "Acrílico",
        ["Glass_LiquidGlass"] = "Cristal líquido",
        ["Row_MinimizeUsing"] = "Minimizar ventanas con",
        ["Minimize_Suck"] = "Efecto de succión",
        ["Minimize_Scale"] = "Efecto de escala",
        ["Minimize_Genie"] = "Efecto genio",
        ["Label_EffectSpeed"] = "Velocidad del efecto",
        ["Caption_Slow"] = "Lenta",
        ["Caption_Default"] = "Predeterminada",
        ["Caption_Fast"] = "Rápida",
        ["Toggle_ShowIndicators"] = "Mostrar indicadores de las apps abiertas",
        ["Toggle_AnimateOpening"] = "Animar la apertura de aplicaciones",
        ["Toggle_MinimizeIntoIcon"] = "Minimizar las ventanas en el icono de la app",
        ["Toggle_HideTaskbar"] = "Ocultar automáticamente la barra de tareas de Windows",
        ["Tray_ShowHideDock"] = "Mostrar / Ocultar Dock",
        ["Tray_HideTaskbar"] = "Ocultar barra de tareas",
        ["Tray_Theme"] = "Tema",
        ["Menu_DockPreferences"] = "Preferencias del Dock…",
        ["Menu_AboutDockable"] = "Acerca de Dockable",
        ["Menu_Exit"] = "Salir",
        ["Menu_EmptyRecycleBin"] = "Vaciar Papelera de reciclaje",
        ["Menu_QuitDockable"] = "Salir de Dockable",
        ["Menu_NewWindow"] = "Nueva ventana",
        ["Menu_Rename"] = "Cambiar nombre",
        ["Menu_Options"] = "Opciones",
        ["Menu_KeepInDock"] = "Mantener en el Dock",
        ["Menu_OpenAtLogin"] = "Abrir al iniciar sesión",
        ["Menu_ShowInExplorer"] = "Mostrar en el Explorador",
        ["Menu_ShowAllWindows"] = "Mostrar todas las ventanas",
        ["Menu_Quit"] = "Salir",
        ["Menu_ForceQuit"] = "Forzar salida",
        ["Dialog_AddToStartup"] = "¿Quieres añadir Dockable al inicio?",
        ["Dialog_ReplicatePinsSingular"] = "Se ha anclado un nuevo acceso directo a la barra de tareas. ¿Quieres replicarlo en el Dock?",
        ["Dialog_ReplicatePinsPlural"] = "Se han anclado nuevos accesos directos a la barra de tareas. ¿Quieres replicarlos en el Dock?",
        ["Dialog_RenameShortcut"] = "Cambiar el nombre de este acceso directo:",
        ["Common_DoNotAskAgain"] = "No volver a preguntar",
        ["Common_Yes"] = "Sí",
        ["Common_No"] = "No",
        ["Common_OK"] = "Aceptar",
        ["Common_Cancel"] = "Cancelar",
        ["Common_Close"] = "Cerrar",
        ["Error_StartupFailed"] = "No se pudo iniciar Dockable:\n\n{0}\n\nLos detalles se escribieron en %APPDATA%\\Dockable\\crash.log.",
        ["About_Tagline"] = "Un Dock al estilo de macOS para Windows 11",
        ["About_Version"] = "Versión {0}",
        ["About_Body"] = "Dockable lleva la experiencia del Dock de macOS a Windows 11: iconos que se amplían, una barra de cristal y una minimización estilo genio. Está desarrollado con C# y WPF sobre .NET 9 (x64), con interoperabilidad nativa de Win32 mediante CsWin32, MVVM con CommunityToolkit.Mvvm y un icono en la bandeja del sistema con H.NotifyIcon. Inspirado en el Dock de macOS de Apple.",
        ["About_CreatedBy"] = "Creado por",
    };

    private static readonly IReadOnlyDictionary<string, string> Ukrainian = new Dictionary<string, string>
    {
        ["Window_DockPreferences"] = "Параметри Dock",
        ["Section_System"] = "Система",
        ["Section_Appearance"] = "Зовнішній вигляд",
        ["Section_Dock"] = "Dock",
        ["Section_Taskbar"] = "Панель завдань",
        ["Row_Language"] = "Мова",
        ["Row_OpenAtLogin"] = "Запускати під час входу",
        ["Link_StartupApps"] = "Програми автозапуску",
        ["Theme_Light"] = "Світла",
        ["Theme_Dark"] = "Темна",
        ["Theme_Auto"] = "Авто",
        ["Label_Size"] = "Розмір",
        ["Caption_Small"] = "Малий",
        ["Caption_Large"] = "Великий",
        ["Label_Magnification"] = "Збільшення",
        ["Caption_Off"] = "Вимкнено",
        ["Row_Position"] = "Розташування на екрані",
        ["Position_Bottom"] = "Знизу",
        ["Position_Left"] = "Ліворуч",
        ["Position_Right"] = "Праворуч",
        ["Position_Top"] = "Зверху",
        ["Row_GlassEffect"] = "Ефект скла",
        ["Glass_Translucent"] = "Напівпрозорий",
        ["Glass_Acrylic"] = "Акрил",
        ["Glass_LiquidGlass"] = "Рідке скло",
        ["Row_MinimizeUsing"] = "Згортати вікна за допомогою",
        ["Minimize_Suck"] = "Ефект всмоктування",
        ["Minimize_Scale"] = "Ефект масштабування",
        ["Minimize_Genie"] = "Ефект джина",
        ["Label_EffectSpeed"] = "Швидкість ефекту",
        ["Caption_Slow"] = "Повільно",
        ["Caption_Default"] = "Стандартно",
        ["Caption_Fast"] = "Швидко",
        ["Toggle_ShowIndicators"] = "Показувати індикатори відкритих програм",
        ["Toggle_AnimateOpening"] = "Анімувати відкриття програм",
        ["Toggle_MinimizeIntoIcon"] = "Згортати вікна у значок програми",
        ["Toggle_HideTaskbar"] = "Автоматично приховувати панель завдань Windows",
        ["Tray_ShowHideDock"] = "Показати / Сховати Dock",
        ["Tray_HideTaskbar"] = "Сховати панель завдань",
        ["Tray_Theme"] = "Тема",
        ["Menu_DockPreferences"] = "Параметри Dock…",
        ["Menu_AboutDockable"] = "Про Dockable",
        ["Menu_Exit"] = "Вихід",
        ["Menu_EmptyRecycleBin"] = "Очистити Кошик",
        ["Menu_QuitDockable"] = "Вийти з Dockable",
        ["Menu_NewWindow"] = "Нове вікно",
        ["Menu_Rename"] = "Перейменувати",
        ["Menu_Options"] = "Параметри",
        ["Menu_KeepInDock"] = "Залишити в Dock",
        ["Menu_OpenAtLogin"] = "Запускати під час входу",
        ["Menu_ShowInExplorer"] = "Показати в Провіднику",
        ["Menu_ShowAllWindows"] = "Показати всі вікна",
        ["Menu_Quit"] = "Завершити",
        ["Menu_ForceQuit"] = "Примусово завершити",
        ["Dialog_AddToStartup"] = "Додати Dockable до автозапуску?",
        ["Dialog_ReplicatePinsSingular"] = "До панелі завдань закріплено новий ярлик. Відтворити його в Dock?",
        ["Dialog_ReplicatePinsPlural"] = "До панелі завдань закріплено нові ярлики. Відтворити їх у Dock?",
        ["Dialog_RenameShortcut"] = "Перейменувати цей ярлик:",
        ["Common_DoNotAskAgain"] = "Більше не запитувати",
        ["Common_Yes"] = "Так",
        ["Common_No"] = "Ні",
        ["Common_OK"] = "OK",
        ["Common_Cancel"] = "Скасувати",
        ["Common_Close"] = "Закрити",
        ["Error_StartupFailed"] = "Не вдалося запустити Dockable:\n\n{0}\n\nПодробиці записано у %APPDATA%\\Dockable\\crash.log.",
        ["About_Tagline"] = "Dock у стилі macOS для Windows 11",
        ["About_Version"] = "Версія {0}",
        ["About_Body"] = "Dockable переносить досвід Dock з macOS на Windows 11 — збільшення значків, скляна панель і згортання у стилі джина. Створено на C# і WPF на основі .NET 9 (x64), з нативною взаємодією Win32 через CsWin32, MVVM за допомогою CommunityToolkit.Mvvm і значком у системному лотку від H.NotifyIcon. Натхненням слугував Dock з macOS від Apple.",
        ["About_CreatedBy"] = "Створив",
    };

    private static readonly IReadOnlyDictionary<string, string> ChineseSimplified = new Dictionary<string, string>
    {
        ["Window_DockPreferences"] = "Dock 偏好设置",
        ["Section_System"] = "系统",
        ["Section_Appearance"] = "外观",
        ["Section_Dock"] = "Dock",
        ["Section_Taskbar"] = "任务栏",
        ["Row_Language"] = "语言",
        ["Row_OpenAtLogin"] = "登录时打开",
        ["Link_StartupApps"] = "启动应用",
        ["Theme_Light"] = "浅色",
        ["Theme_Dark"] = "深色",
        ["Theme_Auto"] = "自动",
        ["Label_Size"] = "大小",
        ["Caption_Small"] = "小",
        ["Caption_Large"] = "大",
        ["Label_Magnification"] = "放大",
        ["Caption_Off"] = "关闭",
        ["Row_Position"] = "屏幕上的位置",
        ["Position_Bottom"] = "底部",
        ["Position_Left"] = "左侧",
        ["Position_Right"] = "右侧",
        ["Position_Top"] = "顶部",
        ["Row_GlassEffect"] = "玻璃效果",
        ["Glass_Translucent"] = "半透明",
        ["Glass_Acrylic"] = "亚克力",
        ["Glass_LiquidGlass"] = "液态玻璃",
        ["Row_MinimizeUsing"] = "最小化窗口时使用",
        ["Minimize_Suck"] = "吸入效果",
        ["Minimize_Scale"] = "缩放效果",
        ["Minimize_Genie"] = "神奇效果",
        ["Label_EffectSpeed"] = "效果速度",
        ["Caption_Slow"] = "慢",
        ["Caption_Default"] = "默认",
        ["Caption_Fast"] = "快",
        ["Toggle_ShowIndicators"] = "显示已打开应用程序的指示器",
        ["Toggle_AnimateOpening"] = "打开应用时显示动画",
        ["Toggle_MinimizeIntoIcon"] = "将窗口最小化为应用程序图标",
        ["Toggle_HideTaskbar"] = "自动隐藏 Windows 任务栏",
        ["Tray_ShowHideDock"] = "显示 / 隐藏 Dock",
        ["Tray_HideTaskbar"] = "隐藏任务栏",
        ["Tray_Theme"] = "主题",
        ["Menu_DockPreferences"] = "Dock 偏好设置…",
        ["Menu_AboutDockable"] = "关于 Dockable",
        ["Menu_Exit"] = "退出",
        ["Menu_EmptyRecycleBin"] = "清空回收站",
        ["Menu_QuitDockable"] = "退出 Dockable",
        ["Menu_NewWindow"] = "新建窗口",
        ["Menu_Rename"] = "重命名",
        ["Menu_Options"] = "选项",
        ["Menu_KeepInDock"] = "保留在 Dock 中",
        ["Menu_OpenAtLogin"] = "登录时打开",
        ["Menu_ShowInExplorer"] = "在资源管理器中显示",
        ["Menu_ShowAllWindows"] = "显示所有窗口",
        ["Menu_Quit"] = "退出",
        ["Menu_ForceQuit"] = "强制退出",
        ["Dialog_AddToStartup"] = "是否将 Dockable 添加到启动项？",
        ["Dialog_ReplicatePinsSingular"] = "已有新的快捷方式固定到任务栏。要在 Dock 上复制它吗？",
        ["Dialog_ReplicatePinsPlural"] = "已有新的快捷方式固定到任务栏。要在 Dock 上复制它们吗？",
        ["Dialog_RenameShortcut"] = "重命名此快捷方式：",
        ["Common_DoNotAskAgain"] = "不再询问",
        ["Common_Yes"] = "是",
        ["Common_No"] = "否",
        ["Common_OK"] = "好",
        ["Common_Cancel"] = "取消",
        ["Common_Close"] = "关闭",
        ["Error_StartupFailed"] = "Dockable 启动失败：\n\n{0}\n\n详细信息已写入 %APPDATA%\\Dockable\\crash.log。",
        ["About_Tagline"] = "适用于 Windows 11 的 macOS 风格 Dock",
        ["About_Version"] = "版本 {0}",
        ["About_Body"] = "Dockable 将 macOS 的 Dock 体验带到 Windows 11——图标放大、玻璃栏以及神灯式最小化。它使用 C# 和 WPF 基于 .NET 9（x64）构建，通过 CsWin32 进行原生 Win32 互操作，使用 CommunityToolkit.Mvvm 实现 MVVM，并使用 H.NotifyIcon 提供系统托盘图标。灵感来自 Apple 的 macOS Dock。",
        ["About_CreatedBy"] = "作者",
    };

    // Declared last so every per-language table field is initialized before this captures them
    // (static field initializers run in textual order).
    /// <summary>Culture code → (key → localized string).</summary>
    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Tables =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["en"] = English,
            ["pt-BR"] = PortugueseBR,
            ["es"] = Spanish,
            ["uk"] = Ukrainian,
            ["zh-Hans"] = ChineseSimplified,
        };
}
