name: Dockable CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Dockable.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Run unit tests
      run: dotnet test

    - name: Restore solution
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build solution (x64 + ARM64)
      run: |
        msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=x64
        msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=ARM64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Dockable-Builds
        path: Dockable/bin/${{ matrix.configuration }}
